// <auto-generated />
namespace RejestrOsobZaginionych.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPersonHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPersonHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202106222230568_Add Person History"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
